Update one_process.yml

diff --git a/.github/workflows/one_process.yml b/.github/workflows/one_process.yml
--- a/.github/workflows/one_process.yml
+++ b/.github/workflows/one_process.yml
@@ -92,6 +92,13 @@ jobs:
           ${{ runner.os }}-flutter-
 
 
+    - name: Debug: List android-35 SDK folder
+      run: |
+        export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-$ANDROID_HOME}"
+        ls -l $ANDROID_SDK_ROOT/platforms/android-35 || echo "android-35 not found"
+        ls -l $ANDROID_SDK_ROOT/platforms || echo "platforms folder not found"
+
+
     - name: Build APK
       run: |
         flutter clean
